version: '3.8'

services:
    domjudge-jh:
        image: acmfsu/judgehost:7.3.3
        privileged: true
        restart: always
        secrets:
            - domjudge_jh_password
        environment:
            CONTAINER_TIMEZONE: America/New_York
            JUDGEDAEMON_USERNAME: judgehost
            JUDGEDAEMON_PASSWORD_FILE: /run/secrets/domjudge_jh_password
            DOMSERVER_BASEURL: http://domserver/
        volumes:  
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            - domjudge-jh-backend
    bastion-jh:
        image: acmfsu/judgehost:7.3.3
        privileged: true
        restart: always
        secrets:
            - bastion_jh_password
        environment:
            CONTAINER_TIMEZONE: America/New_York
            JUDGEDAEMON_USERNAME: judgehost
            JUDGEDAEMON_PASSWORD_FILE: /run/secrets/bastion_jh_password
            DOMSERVER_BASEURL: http://domserver/
        volumes:  
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            - bastion-jh-backend
secrets:
    domjudge_jh_password:
        file: config/domjudge_jh_password.secret
    bastion_jh_password:
        file: config/bastion_jh_password.secret
networks:
    domjudge-jh-backend:
        external: true
        name: domjudge_jh-backend
    bastion-jh-backend:
        external: true
        name: bastion_jh-backend
