version: '3.8'
services:
  nginx:
    image: nginx:latest
    labels:
      - nginx_proxy=true
    ports:
      - 80:80
      - 433:433
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - backend

  dockergen:
    image: helder/docker-gen:latest
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    command: -notify "docker-label-sighup nginx_proxy" -watch -only-exposed -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  acme-companion:
    #container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion:latest
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
      - DEFAULT_EMAIL=fsu.cs.acm@gmail.com
      

volumes:
  acme:
  certs:
  conf:
  html:
  vhost:

networks:
  backend:
    name: proxied-apps