version: '3.8'
services:
    nginx-proxy:
		image: nginxproxy/nginx-proxy:0.9
        container_name: nginx-proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - 'certs:/etc/nginx/certs'
            - 'vhost:/etc/nginx/vhost.d'
            - 'html:/usr/share/nginx/html'
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - 'config/nginx-proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro'
        deploy:
            replicas: 2
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
        