version: '3.8'
services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy:0.9
        ports:
            - 80:80
            - 443:443
        volumes:
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./config/nginx-proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
        networks:
            - frontend
            - backend
        deploy:
            replicas: 2
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    acme-companion:
        image: nginxproxy/acme-companion:2.1
        env_file:
            - ./envs/acme.env
        volumes:
            - acme:/etc/acme.sh
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - acme-companion
        deploy:
            replicas: 2
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
volumes:
    acme:
    certs:
    html:
    vhost:
networks:
    frontend:
        name: acme-companion
    backend:
        name: proxied-apps
        