version: '3.8'
services:
    domserver:
        image: domjudge/domserver:7.3.3
        env_file:
            - ./envs/domserver.env
        volumes:
            - ./config/initial_admin_password.secret:/opt/domjudge/domserver/etc/initial_admin_password.secret:ro 
        networks:
            - frontend
            - domserver-jh-backend
            - domserver-db-backend
    mariadb:
        image: mariadb:10.6-focal
        env_file:
            - ./envs/db.env
        volumes:
            - domserver_db_data:/var/lib/mysql
        networks:
            - frontend
            - domserver-db-backend
            - domserver-jh-backend        
volumes:
    domserver_db_data:
networks:
    frontend:
        external: true
        name: proxied-apps
    domserver-jh-backend:
        name: domserver-jh-backend
        attachable: true
    domserver-db-backend:
        name: domserver-db-backend
    