version: '3.8'

services:
    django:
        build:
            context: ../..
            args:
                REQUIREMENTS: requirements-dev.txt
        image: contestsuite:dev
        command: /app/docker/start.sh server debug
        environment:
            # Django
            DEBUG: 'True'
            CACHE_LOCATION: redis://redis:6379/0
            
            # Celery
            CELERY_BACKEND: redis://redis:6379/1
            CELERY_BROKER: amqp://rabbitmq:5672

            # Database
            SQL_HOST: 'mariadb'
            SQL_PORT: '3306'
            SQL_DATABASE: 'contestsuite'
            SQL_USER: 'contestadmin'
            SQL_PASSWORD: 'seminoles1!'
        ports:
            - 8000:8000
        volumes:
            - ../../src:/app
            - deployment_scripts:/app/docker
        networks:
            - contestsuite
        depends_on:
            - redis
            - rabbitmq
            - mariadb
            - celery_worker
    celery_beat:
        image: contestsuite:dev
        command: /app/docker/start.sh beat
        environment:
            # Django
            DEBUG: 'True'

            # Celery
            CELERY_BACKEND: redis://redis:6379/1
            CELERY_BROKER: amqp://rabbitmq:5672

            # Database
            SQL_HOST: 'mariadb'
            SQL_PORT: '3306'
            SQL_DATABASE: 'contestsuite'
            SQL_USER: 'contestadmin'
            SQL_PASSWORD: 'seminoles1!'
        volumes:
            - ../../src:/app
            - deployment_scripts:/app/docker
        networks:
            - contestsuite
        depends_on:
            - celery_worker
            - redis
            - rabbitmq
            - mariadb
    celery_worker:
        image: contestsuite:dev
        command: /app/docker/start.sh worker
        environment:
            # Django
            DEBUG: 'True'

            # Celery
            CELERY_BACKEND: redis://redis:6379/1
            CELERY_BROKER: amqp://rabbitmq:5672

            # Database
            SQL_HOST: 'mariadb'
            SQL_PORT: '3306'
            SQL_DATABASE: 'contestsuite'
            SQL_USER: 'contestadmin'
            SQL_PASSWORD: 'seminoles1!'
            
            # Discord
            ANNOUNCEMENT_WEBHOOK_URL: # Webhook URL of the contest announcements channel
            BOT_CHANNEL_WEBHOOK_URL: # Webhook URL of the bot command channel
            GUILD_ID: # Discord Server ID
            SCRAPE_BOT_TOKEN: # Token for the member list scraping bot
        volumes:
            - ../../src:/app
            - deployment_scripts:/app/docker
        networks:
            - contestsuite
        depends_on:
            - redis
            - rabbitmq
            - mariadb
    flower:
        image: mher/flower:latest
        command: celery --broker=amqp://rabbitmq:5672// flower --broker_api=http://rabbitmq:15672/api/vhost
        environment:
            CELERY_TIMEZONE: America/New_York
        ports:
            - 5555:5555
        volumes:
            - flower:/data
        networks:
            - contestsuite
        depends_on:
            - redis
            - rabbitmq
            - celery_worker
    mariadb:
        image: mariadb:10.6-focal
        environment:
            MARIADB_ROOT_PASSWORD: 'rootpw'
            MARIADB_DATABASE: 'contestsuite'
            MARIADB_USER: 'contestadmin'
            MARIADB_PASSWORD: 'seminoles1!'
        volumes:
            - django_db:/var/lib/mysql
        networks:
            - contestsuite
    redis:
        image: redis:5-buster
        volumes:
            - redis:/data
        networks:
            - contestsuite
    rabbitmq:
        image: rabbitmq:3-management-alpine
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        networks:
            - contestsuite       
volumes:
    deployment_scripts:
    django_db:
    flower:
    redis:
    rabbitmq:
networks:
    contestsuite:
        name: contestsuite
