# Generated by Django 4.2.26 on 2026-03-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfg', '0003_auto_20220904_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordmember',
            name='discriminator',
        ),
        migrations.RemoveField(
            model_name='lfgprofile',
            name='discord_discriminator',
        ),
    ]
