version: '3.8'
services:
    dj-mariadb:
        image: mariadb:10.6-focal
        environment:
            - MYSQL_ROOT_PASSWORD=rootpw
            - MYSQL_USER=domjudge
            - MYSQL_PASSWORD=djpw
            - MYSQL_DATABASE=domjudge
        networks:
            - ds-db-backend
    domserver:
        image: domjudge/domserver:7.3.3
        environment:
            - MYSQL_HOST=dj-mariadb
            - MYSQL_USER=domjudge
            - MYSQL_DATABASE=domjudge
            - MYSQL_PASSWORD=djpw
            - MYSQL_ROOT_PASSWORD=rootpw
            - VIRTUAL_HOST=domjudge.cs.fsu.edu
        networks:
            - frontend
            - ds-jh-backend
            - ds-db-backend
    judgehost:
        image: domjudge/judgehost:7.3.3
        volumes:
            - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
        environment:
            - DAEMON_ID=0
        networks:
            - ds-jh-backend        
networks:
    frontend:
        external: true
        name: proxied-apps
    ds-jh-backend:
        name: ds-jh-backend
    ds-db-backend:
        name: ds-db-backend
    