version: '3.8'
services:
    mariadb:
        image: mariadb:10.6-focal
        environment:
            - MYSQL_ROOT_PASSWORD=rootpw
            - MYSQL_USER=domjudge
            - MYSQL_PASSWORD=djpw
            - MYSQL_DATABASE=domjudge
        networks:
            - ds-db-backend
    domserver:
        image: domjudge/domserver:7.3.3
        environment:
            - MYSQL_HOST=dj-mariadb
            - MYSQL_USER=domjudge
            - MYSQL_DATABASE=domjudge
            - MYSQL_PASSWORD=djpw
            - MYSQL_ROOT_PASSWORD=rootpw
            - VIRTUAL_HOST=domjudge.cs.fsu.edu
        volumes:
            - ./config/initial_admin_password.secret:/opt/domjudge/domserver/etc/initial_admin_password.secret:ro
            # - ./config/restapi.secret:/opt/domjudge/domserver/etc/restapi.secret:ro
        networks:
            - frontend
            - ds-jh-backend
            - ds-db-backend        
networks:
    frontend:
        external: true
        name: proxied-apps
    ds-jh-backend:
        name: ds-jh-backend
    ds-db-backend:
        name: ds-db-backend
    