# Generated by Django 4.2.20 on 2025-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='sponsors')),
                ('url', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
