# Generated by Django 4.2.20 on 2025-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, help_text='Lower numbers appear first. Blank rankings appear last.', null=True),
        ),
    ]
