version: '3.8'
services:
    judgehost_0:
        image: domjudge/judgehost:7.3.3
        env_file:
            - ./envs/judgehost.env
        environment:
            DAEMON_ID: 0
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            - domserver-jh-backend
networks:
    default:
        external: true
        name: domserver-jh-backend
    