version: '3.8'
services:
    judgehost_0:
        image: domjudge/judgehost:7.3.3
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        environment:
            - DAEMON_ID=0
            - DOMSERVER_BASEURL=http://domserver/
            - JUDGEDAEMON_PASSWORD=anothertestpass1!        
networks:
    default:
        external: true
        name: ds-jh-backend
    