version: '3.8'

services:
    nginx:
        image: nginx:mainline
        environment:
            LETSENCRYPT_HOST: contest.cs.fsu.edu
            VIRTUAL_HOST: contest.cs.fsu.edu
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - django_static:/usr/share/nginx/html/static:ro
        networks:
            - frontend
            - nginx-backend
        deploy:
            replicas: 2
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback            
    django:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh server
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_django_key
            - contestsuite_hashid_key
            - contestsuite_email_user
            - contestsuite_email_password
            - contestsuite_discord_guild_id
        environment:
            # Django
            DEBUG: 'False'
            SECRET_KEY: /run/secrets/contestsuite_django_key # Project secret key
            ALLOWED_HOSTS: contest.cs.fsu.edu
            CACHE_TIMEOUT: 300
            CACHE_LOCATION: redis://redis:6379/0

            # Celery
            CELERY_BACKEND: redis://redis:6379/1
            CELERY_BROKER: amqp://rabbitmq:5672

            # Email
            EMAIL_HOST: mail2.cs.fsu.edu
            EMAIL_USER: /run/secrets/contestsuite_email_user
            EMAIL_PASSWORD: /run/secrets/contestsuite_email_password
            EMAIL_USE_TLS: 'True'

            # Database
            SQL_HOST: mariadb
            SQL_PORT: 3306
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password

            # Discord
            GUILD_ID: /run/secrets/contestsuite_discord_guild_id # ID of Discord server

            # Hashid Module 
            HASHID_FIELD_SALT: /run/secrets/contestsuite_hashid_key # Global Salt
        volumes:
            - django_app:/app/media
            - django_static:/app/static
        networks:
            - nginx-backend
            - mariadb-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    scrape_bot:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh bot
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_bot_channel_name
            - contestsuite_discord_guild_id
            - contestsuite_scrapebot_token
        environment:
            # Django
            DEBUG: 'False'

            # Database
            SQL_HOST: mariadb
            SQL_PORT: 3306
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password

            # Discord
            BOT_CHANNEL: /run/secrets/contestsuite_bot_channel_name # Name of command channel
            GUILD_ID: /run/secrets/contestsuite_discord_guild_id # ID of Discord server
            SCRAPE_BOT_TOKEN: /run/secrets/contestsuite_scrapebot_token # Token for integrated bot
        networks:
            - mariadb-backend
        deploy:
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    celery_worker:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh worker
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_django_key
            - contestsuite_email_user
            - contestsuite_email_password
            - contestsuite_announcement_channel_url
            - contestsuite_bot_channel_url
        environment:
            # Django
            DEBUG: 'False'
            SECRET_KEY: /run/secrets/contestsuite_django_key # Project secret key
            ALLOWED_HOSTS: contest.cs.fsu.edu

            # Celery
            CELERY_BACKEND: redis://redis:6379/1
            CELERY_BROKER: amqp://rabbitmq:5672

            # Email
            EMAIL_HOST: mail2.cs.fsu.edu
            EMAIL_USER: /run/secrets/contestsuite_email_user
            EMAIL_PASSWORD: /run/secrets/contestsuite_email_password
            EMAIL_USE_TLS: 'True'

            # Database
            SQL_HOST: mariadb
            SQL_PORT: 3306
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password

            # Discord
            ANNOUNCEMENT_WEBHOOK_URL: /run/secrets/contestsuite_announcement_channel_url # URL of announcement channel webhook
            BOT_CHANNEL_WEBHOOK_URL: /run/secrets/contestsuite_bot_channel_url # URL of bot control channel webhook
        volumes:
            - django_app:/app/media
            - django_static:/app/static
        networks:
            - mariadb-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    celery_beat:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh beat
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
        environment:
            # Django
            DEBUG: 'False'

            # Celery
            CELERY_BACKEND: redis://redis:6379/1
            CELERY_BROKER: amqp://rabbitmq:5672

            # Database
            SQL_HOST: mariadb
            SQL_PORT: 3306
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password
        volumes:
            - django_static:/app/static
        networks:
            - mariadb-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    flower:
        image: mher/flower:latest
        command: celery --broker=amqp://rabbitmq:5672// flower --broker_api=http://guest:guest@rabbitmq:15672/api/vhost --url_prefix=flower --basic_auth=contestadmin:seminoles1!
        environment:
            CELERY_TIMEZONE: America/New_York
        volumes:
            - flower:/data
        networks:
            - nginx-backend
            - rabbitmq-backend
        deploy:
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    mariadb:
        image: mariadb:10.6-focal
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_db_root_password
        environment:
            MARIADB_DATABASE: /run/secrets/contestsuite_db_name
            MARIADB_USER: /run/secrets/contestsuite_db_user
            MARIADB_PASSWORD: /run/secrets/contestsuite_db_password
            MARIADB_ROOT_PASSWORD: /run/secrets/contestsuite_db_root_password
        volumes:
            - django_db:/var/lib/mysql
        networks:
            - mariadb-backend
        deploy:
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    redis:
        image: redis:5-buster
        volumes:
            - redis:/data
        networks:
            - redis-backend
        deploy:
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    rabbitmq:
        image: rabbitmq:3-management
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        networks:
            - rabbitmq-backend
        deploy:
            restart_policy:
                max_attempts: 10
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
secrets:
    # Database
    contestsuite_db_name:
        external: true
    contestsuite_db_user:
        external: true
    contestsuite_db_password:
        external: true
    contestsuite_db_root_password:
        external: true
    # Secret keys
    contestsuite_django_key:
        external: true
    contestsuite_hashid_key:
        external: true
    # Email
    contestsuite_email_user:
        external: true
    contestsuite_email_password:
        external: true
    # Discord server
    contestsuite_discord_guild_id:
        external: true
    contestsuite_bot_channel_name:
        external: true
    # Discord Webhooks
    contestsuite_announcement_channel_url:
        external: true
    contestsuite_bot_channel_url:
        external: true
    # Scrapebot
    contestsuite_scrapebot_token:
        external: true
volumes:
    django_app:
    django_db:
    django_static:
    flower:
    rabbitmq:
    redis:
networks:
    frontend:
        external: true
        name: proxied-apps
    nginx-backend:
        name: nginx-backend
    mariadb-backend:
        name: mariadb-backend
    redis-backend:
        name: redis-backend
    rabbitmq-backend:
        name: rabbitmq-backend
