version: '3.8'

services:
    nginx:
        image: nginx:mainline
        environment:
            LETSENCRYPT_HOST: contest.cs.fsu.edu
            VIRTUAL_HOST: contest.cs.fsu.edu
            
            TZ: America/New_York
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - django_static:/usr/share/nginx/html/static/django:ro
            - flower_static:/usr/share/nginx/html/static/flower:ro
        networks:
            - frontend
            - nginx-backend
        deploy:
            replicas: 2
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 120s
            rollback_config:
                delay: 5s
                monitor: 60s
            update_config:
                parallelism: 1
                delay: 5s
                monitor: 60s
                failure_action: rollback            
    django:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh server
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_django_key
            - contestsuite_hashid_key
            - contestsuite_email_user
            - contestsuite_email_password
            - contestsuite_discord_guild_id
        environment:
            # Django
            SECRET_KEY: /run/secrets/contestsuite_django_key # Project secret key
            ALLOWED_HOSTS: contest.cs.fsu.edu

            # Email
            EMAIL_HOST: mail2.cs.fsu.edu
            EMAIL_USER: /run/secrets/contestsuite_email_user
            EMAIL_PASSWORD: /run/secrets/contestsuite_email_password
            EMAIL_USE_TLS: 'True'

            # Database
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password

            # Discord
            GUILD_ID: /run/secrets/contestsuite_discord_guild_id # ID of Discord server

            # Hashid Module 
            HASHID_FIELD_SALT: /run/secrets/contestsuite_hashid_key # Global Salt
        volumes:
            - django_app:/app/media
            - django_static:/app/static
        networks:
            - nginx-backend
            - db-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 60s
            rollback_config:
                monitor: 75s
            update_config:
                monitor: 75s
                failure_action: rollback
    scrape_bot:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh bot
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_bot_channel_name
            - contestsuite_discord_guild_id
            - contestsuite_scrapebot_token
        environment:
            # Database
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password

            # Discord
            BOT_CHANNEL: /run/secrets/contestsuite_bot_channel_name # Name of command channel
            GUILD_ID: /run/secrets/contestsuite_discord_guild_id # ID of Discord server
            SCRAPE_BOT_TOKEN: /run/secrets/contestsuite_scrapebot_token # Token for integrated bot
        volumes:
            - django_static:/app/static
        networks:
            - db-backend
        deploy:
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 60s
            rollback_config:
                monitor: 75s
            update_config:
                monitor: 75s
                failure_action: rollback
    celery_worker:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh worker
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_django_key
            - contestsuite_email_user
            - contestsuite_email_password
            - contestsuite_announcement_channel_url
            - contestsuite_bot_channel_url
        environment:
            # Django
            SECRET_KEY: /run/secrets/contestsuite_django_key # Project secret key
            ALLOWED_HOSTS: contest.cs.fsu.edu

            # Email
            EMAIL_HOST: mail2.cs.fsu.edu
            EMAIL_USER: /run/secrets/contestsuite_email_user
            EMAIL_PASSWORD: /run/secrets/contestsuite_email_password
            EMAIL_USE_TLS: 'True'

            # Database
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password

            # Discord
            ANNOUNCEMENT_WEBHOOK_URL: /run/secrets/contestsuite_announcement_channel_url # URL of announcement channel webhook
            BOT_CHANNEL_WEBHOOK_URL: /run/secrets/contestsuite_bot_channel_url # URL of bot control channel webhook
        volumes:
            - django_app:/app/media
            - django_static:/app/static
        networks:
            - db-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 60s
            rollback_config:
                monitor: 75s
            update_config:
                monitor: 75s
                failure_action: rollback
    celery_beat:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh beat
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
        environment:
            # Database
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password
        volumes:
            - django_static:/app/static
        networks:
            - db-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 60s
            rollback_config:
                monitor: 75s
            update_config:
                monitor: 75s
                failure_action: rollback
    celery_flower:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh flower
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_flower_user
            - contestsuite_flower_password
            - contestsuite_flower_cookie_key
        environment:
            # Database
            SQL_DATABASE: /run/secrets/contestsuite_db_name
            SQL_USER: /run/secrets/contestsuite_db_user
            SQL_PASSWORD: /run/secrets/contestsuite_db_password

            # Flower
            FLOWER_BROKER_API: http://guest:guest@rabbitmq:15672/api/vhost
            FLOWER_USER: /run/secrets/contestsuite_flower_user
            FLOWER_PASSWORD: /run/secrets/contestsuite_flower_password
            FLOWER_COOKIE_KEY: /run/secrets/contestsuite_flower_cookie_key
        volumes:
            - django_static:/app/static
            - flower_static:/usr/local/lib/python3.9/site-packages/flower/static
        networks:
            - nginx-backend
            - db-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 60s
            rollback_config:
                monitor: 75s
            update_config:
                monitor: 75s
                failure_action: rollback
    mariadb:
        image: mariadb:10.6-focal
        secrets:
            - contestsuite_db_name
            - contestsuite_db_user
            - contestsuite_db_password
            - contestsuite_db_root_password
        environment:
            MARIADB_DATABASE_FILE: /run/secrets/contestsuite_db_name
            MARIADB_USER_FILE: /run/secrets/contestsuite_db_user
            MARIADB_PASSWORD_FILE: /run/secrets/contestsuite_db_password
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/contestsuite_db_root_password
        volumes:
            - django_db:/var/lib/mysql
        networks:
            - db-backend
        deploy:
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 75s
            rollback_config:
                monitor: 75s
            update_config:
                monitor: 75s
                failure_action: rollback
    redis:
        image: redis:5-buster
        environment:
            TZ: America/New_York
        volumes:
            - redis:/data
        networks:
            - redis-backend
        deploy:
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 75s
            rollback_config:
                monitor: 75s
            update_config:
                monitor: 75s
                failure_action: rollback
    rabbitmq:
        image: rabbitmq:3-management
        environment:
            TZ: America/New_York
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        networks:
            - rabbitmq-backend
        deploy:
            restart_policy:
                delay: 5s
                max_attempts: 10
                window: 75s
            rollback_config:
                monitor: 75s
            update_config:
                monitor: 75s
                failure_action: rollback
secrets:
    # Database
    contestsuite_db_name:
        external: true
    contestsuite_db_user:
        external: true
    contestsuite_db_password:
        external: true
    contestsuite_db_root_password:
        external: true
    # Secret keys
    contestsuite_django_key:
        external: true
    contestsuite_hashid_key:
        external: true
    # Email
    contestsuite_email_user:
        external: true
    contestsuite_email_password:
        external: true
    # Discord server
    contestsuite_discord_guild_id:
        external: true
    contestsuite_bot_channel_name:
        external: true
    # Discord Webhooks
    contestsuite_announcement_channel_url:
        external: true
    contestsuite_bot_channel_url:
        external: true
    # Scrapebot
    contestsuite_scrapebot_token:
        external: true
    # Celery Flower
    contestsuite_flower_user:
        external: true
    contestsuite_flower_password:
        external: true
    contestsuite_flower_cookie_key:
        external: true
volumes:
    django_app:
    django_db:
    django_static:
    flower_static:
    rabbitmq:
    redis:
networks:
    frontend:
        external: true
        name: proxied-apps
    nginx-backend:
        name: contestsuite_nginx-backend
    db-backend:
        name: contestsuite_db-backend
    redis-backend:
        name: contestsuite_redis-backend
    rabbitmq-backend:
        name: contestsuite_rabbitmq-backend
