version: '3.8'

services:
    nginx:
        image: nginx:mainline
        environment:
            LETSENCRYPT_HOST: contest.cs.fsu.edu
            VIRTUAL_HOST: contest.cs.fsu.edu
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - django_static:/usr/share/nginx/html/static:ro
        networks:
            - frontend
            - nginx-backend
        deploy:
            replicas: 2
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback            
    django:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh server
        environment:
            # Django
            DEBUG: 'False'
            SECRET_KEY: 86@j2=z!=&1r_hoqboog1#*mb$jx=9mf0uw#hrs@lw&7m34sqz
            ALLOWED_HOSTS: contest.cs.fsu.edu
            CACHE_TIMEOUT: 300
            CACHE_LOCATION: redis://redis:6379/0
            TIME_ZONE: America/New_York

            # Celery
            CELERY_BACKEND: redis://redis:6379/1
            CELERY_BROKER: amqp://rabbitmq:5672

            # Email
            EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
            EMAIL_HOST: smtpsubdomain.example.com
            EMAIL_PORT: 465
            EMAIL_USER: user@example.com
            EMAIL_PASSWORD: examplepass
            EMAIL_USE_SSL: 'False'
            EMAIL_USE_TLS: 'True'
            DEFAULT_FROM_EMAIL: ACM at FSU Programming Contest<acm@cs.fsu.edu>

            # Database
            SQL_HOST: mariadb
            SQL_PORT: 3306
            SQL_DATABASE: contestsuite
            SQL_USER: contestadmin
            SQL_PASSWORD: seminoles1!

            # Discord
            GUILD_ID: 0
        volumes:
            - django_app:/app/media
            - django_static:/app/static
        networks:
            - nginx-backend
            - mariadb-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    celery_worker:
        image: acmfsu/contestsuite:latest
        command: /app/docker/start.sh worker
        environment:
            # Django
            DEBUG: 'False'
            ALLOWED_HOSTS: contest.cs.fsu.edu
            SECRET_KEY: 86@j2=z!=&1r_hoqboog1#*mb$jx=9mf0uw#hrs@lw&7m34sqz

            # Celery
            CELERY_BACKEND: redis://redis:6379/1
            CELERY_BROKER: amqp://rabbitmq:5672
            CELERY_TIMEZONE: America/New_York

            # Email
            EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
            EMAIL_HOST: smtpsubdomain.example.com
            EMAIL_PORT: 465
            EMAIL_USER: user@example.com
            EMAIL_PASSWORD: examplepass
            EMAIL_USE_SSL: 'False'
            EMAIL_USE_TLS: 'True'
            DEFAULT_FROM_EMAIL: ACM at FSU Programming Contest<acm@cs.fsu.edu>

            # Database
            SQL_HOST: mariadb
            SQL_PORT: 3306
            SQL_DATABASE: contestsuite
            SQL_USER: contestadmin
            SQL_PASSWORD: seminoles1!

            # Discord
            ANNOUNCEMENT_WEBHOOK_URL: https://discord.com/api/channel_webhook_url
        volumes:
            - django_app:/app/media
            - django_static:/app/static
        networks:
            - mariadb-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    flower:
        image: mher/flower:latest
        command: celery --broker=amqp://rabbitmq:5672// flower --broker_api=http://guest:guest@rabbitmq:15672/api/vhost --url_prefix=flower --basic_auth=contestadmin:seminoles1!
        environment:
            CELERY_TIMEZONE: America/New_York
        volumes:
            - flower:/data
        networks:
            - nginx-backend
            - rabbitmq-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    mariadb:
        image: mariadb:10.6-focal
        environment:
            MARIADB_ROOT_PASSWORD: rootpw
            MARIADB_DATABASE: contestsuite
            MARIADB_USER: contestadmin
            MARIADB_PASSWORD: seminoles1!
        volumes:
            - django_db:/var/lib/mysql
        networks:
            - mariadb-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    redis:
        image: redis:5-buster
        volumes:
            - redis:/data
        networks:
            - redis-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    rabbitmq:
        image: rabbitmq:3-management
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        networks:
            - rabbitmq-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
volumes:
    django_app:
    django_db:
    django_static:
    flower:
    rabbitmq:
    redis:
networks:
    frontend:
        external: true
        name: proxied-apps
    nginx-backend:
        name: nginx-backend
    mariadb-backend:
        name: mariadb-backend
    redis-backend:
        name: redis-backend
    rabbitmq-backend:
        name: rabbitmq-backend
