version: '3.8'

services:
    nginx:
        image: nginx:1.21-alpine
        environment:
            LETSENCRYPT_HOST: contest.cs.fsu.edu
            VIRTUAL_HOST: contest.cs.fsu.edu
            VIRTUAL_PATH: /
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - django_static_data:/usr/share/nginx/html/static:ro
        networks:
            - frontend
            - nginx-backend
        deploy:
            replicas: 2
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback            
    django:
        image: acmfsu/contestsuite:latest
        # '/start' is the shell script used to run the service
        command: /app/start
        environment:
            - DEBUG=False
            - ALLOWED_HOSTS=contest.cs.fsu.edu,0.0.0.0
            - SECRET_KEY=86@j2=z!=&1r_hoqboog1#*mb$jx=9mf0uw#hrs@lw&7m34sqz

            - CACHE_TIMEOUT=300
            - CACHE_LOCATION=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/1
            - CELERY_BROKER=amqp://rabbitmq:5672

            - MAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
            - MAIL_HOST=smtpsubdomain.example.com
            - MAIL_PORT=465
            - MAIL_USER=user@example.com
            - MAIL_PASSWORD=examplepass

            - SQL_HOST=mariadb
            - SQL_PORT=3306
            - SQL_DATABASE=contestsuite
            - SQL_USER=contestadmin
            - SQL_PASSWORD=seminoles
        volumes:
            - django_app_data:/app/media
            - django_static_data:/app/static
        networks:
            - nginx-backend
            - mariadb-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    celery_worker:
        image: acmfsu/contestsuite:latest
        command: /app/start-celeryworker
        environment:
            - DEBUG=False
            - ALLOWED_HOSTS=contest.cs.fsu.edu,0.0.0.0
            - SECRET_KEY=86@j2=z!=&1r_hoqboog1#*mb$jx=9mf0uw#hrs@lw&7m34sqz

            - CACHE_TIMEOUT=300
            - CACHE_LOCATION=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/1
            - CELERY_BROKER=amqp://rabbitmq:5672

            - MAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
            - MAIL_HOST=smtpsubdomain.example.com
            - MAIL_PORT=465
            - MAIL_USER=user@example.com
            - MAIL_PASSWORD=examplepass

            - SQL_HOST=mariadb
            - SQL_PORT=3306
            - SQL_DATABASE=contestsuite
            - SQL_USER=contestadmin
            - SQL_PASSWORD=seminoles
        volumes:
            - django_app_data:/app/media
        networks:
            - mariadb-backend
            - redis-backend
            - rabbitmq-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    flower:
        image: mher/flower:latest
        command: celery --broker=amqp://rabbitmq:5672// flower --broker_api=http://guest:guest@rabbitmq:15672/api/vhost --url_prefix=flower --basic_auth=contestadmin:seminoles1!
        environment:
            - CELERY_TIMEZONE=America/New_York
        volumes:
            - flower_data:/data
        networks:
            - nginx_backend
            - rabbitmq-backend
    mariadb:
        image: mariadb:10.6-focal
        volumes:
            - django_db_data:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD=rootpw
            - MARIADB_DATABASE=contestsuite
            - MARIADB_USER=contestadmin
            - MARIADB_PASSWORD=seminoles
        networks:
            - mariadb-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    redis:
        image: redis:5-buster
        volumes:
            - redis_data:/data
        networks:
            - redis-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
    rabbitmq:
        image: rabbitmq:3-management-alpine
        volumes:
            - rabbit_data:/var/lib/rabbitmq
        networks:
            - rabbitmq-backend
        deploy:
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
volumes:
    django_app_data:
    django_db_data:
    django_static_data:
    flower_data:
    rabbit_data:
    redis_data:
networks:
    frontend:
        external: true
        name: proxied-apps
    nginx-backend:
        name: nginx-backend
    mariadb-backend:
        name: mariadb-backend
    redis-backend:
        name: redis-backend
    rabbitmq-backend:
        name: rabbitmq-backend