# Generated by Django 4.2.25 on 2025-10-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestadmin', '0006_contest_order_tshirt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='participation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In-Person'), (2, 'Virtual'), (3, 'Hybrid')], default=1),
        ),
    ]
