title: Programming Contest Suite
description: Documentation for FSU-ACM/Programming-Contest-Suite
theme: just-the-docs
repository: FSU-ACM/Programming-Contest-Suite

url: https://fsu-acm.github.io/Programming-Contest-Suite/

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# For copy button on code
enable_copy_code_button: true

# Aux links for the upper right navigation
aux_links:
  "PCS on GitHub":
    - "//github.com/FSU-ACM/Programming-Contest-Suite"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.2.0"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
  # To load mermaid from a local library, also use the `path` key to specify the location of the library; e.g.
  # for (v10+):
  # path: "/assets/js/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.

# External navigation links
nav_external_links:
  - title: Django Documentation
    url: https://docs.djangoproject.com/en/4.2/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Celery Documentation
    url: https://docs.celeryq.dev/en/v5.3.1/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Flower Documentation
    url: https://flower.readthedocs.io/en/latest/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: MariaDB Documentation
    url: https://mariadb.com/kb/en/documentation/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Redis Documentation
    url: https://redis.io/docs/latest/get-started/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: RabbitMQ Documentation
    url: https://www.rabbitmq.com/docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Docker Documentation
    url: https://docs.docker.com/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
    

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

exclude: [.gitignore, docker-compose.yml, Dockerfile, Gemfile, Gemfile.lock]
