title: Programming Contest Suite
description: Documentation for mmcinnestaylor/Programming-Contest-Suite
theme: just-the-docs

url: https://mmcinnestaylor.github.io/Programming-Contest-Suite/

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Aux links for the upper right navigation
aux_links:
  "PCS on GitHub":
    - "//github.com/mmcinnestaylor/Programming-Contest-Suite"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
