version: '3.8'

services:
    acme-companion:
		image: nginxproxy/acme-companion:2.1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - acme:/etc/acme.sh
            - certs
        environment:
			- DEFAULT_EMAIL=fsu.cs.acm@gmail.com
        deploy:
            replicas: 2
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
networks:
    default:
        external: true
        name: proxied-apps
        